

name: Heroku Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
   
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: main

