

name: Main branch workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
   
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build
