

name: AWS EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
   
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Deploy to Amazon EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_SSH_HOST }}
        username: ${{ secrets.AWS_SSH_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: ${{ secrets.AWS_SSH_PORT }}
        source: "., !node_modules"
        target: "~/app/rentx"
        script: |
          cd ~/app/rentx
          yarn --frozen-lockfile
          pm2 restart rentx_api

        

    

